### ISSUE TITLE
[Bug] After Updating, my Favorites list didnt show my current favorites

### ISSUE THREAD

**Issue by trumpetlicks** [Asnivor/MedLaunch#104]
After the update to v0.5.0 the games I currently had in my favorites list weren't showing up in the list.  If I performed a rescrape all of my favorites list however, it showed it updating games, even though they weren't showing up in the list itself.

**Comment by Asnivor** [comment]
Do these games still appear in the show all games or system specific filters? If so do they have a tick in the favorites column?

**Comment by Asnivor** [comment]
@trumpetlicks Unless you can tell me that the games DID appear in the showallgames filter but NOT the favorites filter, then I would suggest that the games had been marked as hidden (this happens automatically if the games were detected as missing/invalid when you did a system scan).

Probably something to do with the archive handling that got introduced in v0.5.0. 

Im going to go out on a limb and say that re-scanning all roms would have resolved this issue. Unless you say otherwise, I'll close this issue come next release.
