### ISSUE TITLE
Mac version ??

### ISSUE THREAD

**Issue by azoreseuropa** [Asnivor/MedLaunch#122]
Nice GUI but what about macOS users ?

**Comment by Asnivor** [comment]
MacOS users will have to use a different front-end and this will not change for the foreseeable future. MedLaunch is built on Windows Presentation Foundation using .NET, and I'm fairly certain WPF will never work on macOS or be ported to .NET Core.

The closest thing that does work on MacOS is Silverlight, and I'm not in a position to undertake a WPF to SL convertion project (especially since it has such a low chance of success anyways).

**Comment by azoreseuropa** [comment]
Thank you.
