### ISSUE TITLE
Can't add Valkyrie Profile to library 

### ISSUE THREAD

**Issue by WizLizard** [Asnivor/MedLaunch#123]
I get this when trying to add the game to the library. There is nothing wrong with the m3u file i double checked also check the cue files. Epsxe detects the game just fine. The game also runs just fine within epsxe and mednafen.
![screenshot 3](https://user-images.githubusercontent.com/12180630/27527355-5a2be394-5a19-11e7-9fb6-ce0eee684bc6.png)

**Comment by Asnivor** [comment]
Could you possibly post the .m3u file here (or the contents of the m3u file)?

Also, if you try to import the first .cue file into MedLaunch rather than the .m3u file does this succeed?

**Comment by WizLizard** [comment]
[Valkyrie Profile.txt](https://github.com/Asnivor/MedLaunch/files/1101281/Valkyrie.Profile.txt)

**Comment by Asnivor** [comment]
Could be a cuefile issue I guess. In order to confirm whether it is a problem with MedLaunch, are you able to run this in mednafen outside of medlaunch?

So for example in a command prompt, can you do something like:

c:\path\to\mednafen.exe "c:\path\to\Valkyrie Profile.m3u"

Does this actually run in mednafen

**Comment by WizLizard** [comment]
Oh yeah it runs fine in mednafen and Epsxe. I can manually launch it
through medlaunch as well and it runs. It just won't add to the library.

**Comment by Asnivor** [comment]
Ok, i've found the problem.

MedLaunch on import gets the .cue files from the .m3u file, then interogates those .cue files to make sure the path to the bin/iso file is valid.

The issue is here:  https://github.com/Asnivor/MedLaunch/blob/master/MedLaunch/Classes/Scanning/DiscScan.cs#L905

Its basically stripping text from the file string, and one of these replace methods is removing "file ". This should strip the start of the text string leaving the .bin filename. But because there is a 'file' in profile its actually looking for:

Valkyrie Pro(Disc1).bin (which obviously does not exist).

I'll get this sorted shortly with some better coding :)

**Comment by WizLizard** [comment]
Ahhh ok that makes sense.
