### ISSUE TITLE
Controller mapping

### ISSUE THREAD

**Issue by Asnivor** [Asnivor/MedLaunch#16]
ToDo: Learn how SDL works :)

**Comment by Asnivor** [comment]
This is very nearly there. Controller configuration through the launcher works for XInput devices (xbox 360 controller), and through directinput, keyboard and directinput controller gamepads/joysticks.

The directinput code *should* process buttons and axis in the same order as mednafen now, but since I only have one directinput controller to test, this will be marked as experimental once it is released.

Still a few keyboard bug-checks remaining.

**Comment by WizLizard** [comment]
Can't seem to get this working in the build you provided with my xbox one controller. I click on a box and it turns red but it doesn't detect any of my inputs for my controller.

**Comment by Asnivor** [comment]
Ok, this could be tricky as I dont have a one controller to test :/ A few questions:

1. Was the controller plugged in *before* you started medlaunch? (controller detection currently only happens once when medlaunch starts)
2. Does keyboard detection work correctly? (ie. when you click on a box then hit a key it returns a mednafen key binding)
3. Can you post the first part of the stdout.txt file (in the mednafen directory) after you have launched a game *with* the xbox one controller plugged in? (I am interested in the 'Initializing joysticks...' part where it should show your gamepad name and unique id)
4. (silly question) Does the controller actually work in mednafen anyway?
5. If you havent already can you configure a controller in mednafen (shift-alt-1 in game), then quit out and open this controller configuration in medlaunch? The UI should show the joystick config lines you have configured. If you can screengrab that and paste it in here it would be most helpful

I'm assuming the xbone controller runs over wireless or bluetooth. That shouldnt make any difference to how xinput or directinput detects it, but it must be something right: :)

Thanks for this.

**Comment by WizLizard** [comment]
Yes the controller has always worked in mednafen. I've always been able to
configure it with the alt shift combo. I use it wirelessly. With the
adapter from Microsoft.

On Mar 8, 2017 5:03 AM, "Asnivor" <notifications@github.com> wrote:

Ok, this could be tricky as I dont have a one controller to test :/ A few
questions:

   1. Was the controller plugged in *before* you started medlaunch?
   (controller detection currently only happens once when medlaunch starts)
   2. Does keyboard detection work correctly? (ie. when you click on a box
   then hit a key it returns a mednafen key binding)
   3. Can you post the first part of the stdout.txt file (in the mednafen
   directory) after you have launched a game *with* the xbox one controller
   plugged in? (I am interested in the 'Initializing joysticks...' part where
   it should show your gamepad name and unique id)
   4. (silly question) Does the controller actually work in mednafen anyway?
   5. If you havent already can you configure a controller in mednafen
   (shift-alt-1 in game), then quit out and open this controller configuration
   in medlaunch? The UI should show the joystick config lines you have
   configured. If you can screengrab that and paste it in here it would be
   most helpful

I'm assuming the xbone controller runs over wireless or bluetooth. That
shouldnt make any difference to how xinput or directinput detects it, but
it must be something right: :)

Thanks for this.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Asnivor/MedLaunch/issues/16#issuecomment-284999326>,
or mute
the thread

**Comment by WizLizard** [comment]
So i must have turned my controller on after launching medlaunch when trying to configure the controller. Made sure that i had it turned on before i launched the software and it worked. Except for the analog toggle button. I was unable to get it to register the xbox one button above the start and select buttons. I'm able to configure it with the alt shift method as always no problem.

**Comment by Asnivor** [comment]
Ok thats better news :)

I'll try and and fix it so directinput and xinput detection are initialised when you open a 'configure controller' window (and disposed when that window is closed) rather than just at application start. If I can get that working it should handle connecting devices after medlaunch has started.

_Analog Toggle Button:_ 
Are you sure that this actually maps in mednafen when configured through shift-ctrl-n? Reason I ask is that I have a crappy directinput gamepad with an analog toggle switch that mednafen does not pick up (from a technical perspective, it is an internal gamepad operation only, that changes the analog sticks to report as analog sticks, rather than just mirroring other digital axis or buttons).

_XBone Button_
I have a similar xbox button on my wired 360 controller (if we are talking about the same thing). When I try to map this in medlaunch the xbox 360 software just pops up a dialog in windows.

Either this button is not being detected correctly in medlaunch, or windows is 'intercepting' the button press before medlaunch can detect. I'll have to look into this further.

**Comment by WizLizard** [comment]
Yes I'm positive it works perfectly configuring through mednafen. Dinput
just doesn't work, never has. What i meant is i use the xbox home button as
my analog toggle button. Not that there is a separate analog button and an
xbox home button. Here is a pic of the xbox one home button that i set to
analog toggle through mednafens shift alt method. Can't get it to register
with your controller config. I also have a wireless adapter for my dual
shock 3 controller that allows it to function in xinput mode. The home
button on it aslo works fine with the shift alt method.

**Comment by WizLizard** [comment]
What I meant about dinput not working is that any dinput controller that
has a similar home button to the xbox one home button i have never been
able to get mednafen to detect it. All other dinput buttons have always
worked. In case that wasn't clear.

**Comment by Asnivor** [comment]
Ahh ok, so the issue basically is that the xbox button does not get detected in mednafen.

I'll work on it.

**Comment by WizLizard** [comment]
It's not detected in the medlaunch controller config you created. It's
configurable and works fine with shift+alt method just fine. Sorry i got
off work at 1:30 am and it's now 4 am so I'm a bit sleepy.

**Comment by Asnivor** [comment]
Sorry, its not you, its me :)

**Comment by WizLizard** [comment]
It's all good.
