### ISSUE TITLE
Localisation detection issue when querying stdout.txt

### ISSUE THREAD

**Issue by Biofreak1987** [Asnivor/MedLaunch#70]
Windows 10 64-bit
.NET Framework 4.6.2
Mednafen 0.9.42

I can't use MedLaunch for playing Mednafen games since v 0.4.0.0. I do always receive the Message "**There was a problem retreiving the Mednafen version. Please check your paths**" when I try to start a game.
The last 0.3.x.x release starts Mednafen without any problems.
A clean install of both the latest MedLaunch and Mednafen release didn't help.

**Comment by retro-wertz** [comment]
im not sure why this is happening for you but  i have been using Medlaunch
since v0.2 something. try using short folder names(no spaces or special
characters) on both medlaunch and mednafen probably(thats how i have them
in mine at least)

and make sure mednafen does work even without using medlaunch

**Comment by Asnivor** [comment]
@Biofreak1987 :  @retro-wertz  gives sound advice.

That particular error message is thrown when MedLaunch is trying to run Mednafen very quickly in the background in order to scrape the Mednafen log file for the Mednafen version.

After you attempt to launch a game through MedLaunch, can you open the stdout.txt file in the mednafen folder (there is a shortcut to do this in MedLaunch's top left 'log' menu) and paste the contents of that file in here?

**Comment by Biofreak1987** [comment]
```
Starte Mednafen 0.9.42
 Build information:
   Compiled with gcc 4.9.4
   Running with MinGW-W64 Runtime 3.3 (stable - rev. 6583) 2014-04-15
   Compiled against zlib 1.2.8, running with zlib 1.2.8(flags=0x00000065)
   Compiled against libiconv 14.1, running with libiconv 14.1
   Compiled against SDL 1.2.15, running with SDL 1.2.15
   Running with libsndfile-1.0.27
 Base directory: D:\Games\Emulators\Mednafen
 Emulation modules: nes snes gb gba pce lynx md pcfx ngp psx ss ssfplay vb wswan sms gg snes_faust pce_fast demo cdplay
 Loading settings from "D:\Games\Emulators\Mednafen\mednafen-09x.cfg"...
  Loaded 3774 valid settings and 1 unknown settings.
 Initializing joysticks...
  Joystick 0 - XInput Unknown Controller - Unique ID: 0000000000010000
 Loading SDL.dll...
Error opening file "SDL.dll": No such file or directory
```

There is a file named SDL.dll in my mednafen directory btw.

**Comment by Asnivor** [comment]
OK, its a localisation issue. MedLaunch is looking at the first line of the log file and expecting 'Starting'. Because yours shows 'Starte' its not proceeding correctly.

I'll try and get a small bugfix release out tomorrow that will certainly fix this

**Comment by Biofreak1987** [comment]
Ok. Thx for the quick response 😃.
